version: "3.9"
services:
  db:
    image: postgres
    container_name: physical_db
    env_file:
      - ./.env.ci
    ports:
      - 5432:5432

  web:
    build: .
    container_name: physical_app
    command: bash entrypoint.sh
    ports:
      - 8000:8000
    env_file:
      - ./.env.ci
    depends_on:
      - db
